#!/bin/sh

#  TCM_GenerateRevisionConfig.sh

# this script needs to be included in the app build scheme prebuild phase using
# ${SRCROOT}/TCM_GenerateRevisionConfig.sh

# You can override TCM_WORKSPACE_ROOT to have a differnt repository layout. Default is having a BuildConfig folder on ../${SOURCE_ROOT}
# YOU CAN CHANGE THIS by defining custom build setting called TCM_WORKSPACE_ROOT

# generate app revision numbers
cd "${SRCROOT}"
REV_SHA1=`git rev-parse HEAD`

# count all the comits which make up the current revision we add 10.000 to this changecount to avoid collitions with former svn revision numbers
GIT_REV=`git rev-list HEAD | wc -l;`
REV=`echo $(( ${GIT_REV} ))`

if [ `git ls-files -m | wc -l` -gt 0 ]; then
	MODIFIED=".1"
fi

YEAR=`date +"%Y"`

cd -

REVISION_CONFIG_FILE="${SRCROOT}/Configs/TCMRevision.xcconfig"

echo "Writing to ${REVISION_CONFIG_FILE}"

echo "Current TCM_APP_REVISION ${TCM_APP_REVISION}"
echo "Current TCM_APP_REVISION_HASH ${TCM_APP_REVISION_HASH}"
echo "Current TCM_APP_BUILD_STYLE ${TCM_APP_BUILD_STYLE}"
echo "Current TCM_APP_BUILD_YEAR ${TCM_APP_BUILD_YEAR}"
echo "Current CONFIGURATION ${CONFIGURATION}"

echo "Setting new TCM_APP_REVISION ${REV}${MODIFIED}"
echo "Setting new TCM_APP_REVISION_HASH ${REV_SHA1}${MODIFIED}"
echo "Setting new TCM_APP_BUILD_STYLE ${CONFIGURATION}"
echo "Setting new TCM_APP_BUILD_YEAR ${YEAR}"

# Write the new config file
cat >"${REVISION_CONFIG_FILE}" <<EOL
//*********    AUTOGENERATED FILE    *********
//*********       DO NOT EDIT        *********

TCM_APP_REVISION = ${REV}${MODIFIED}
TCM_APP_REVISION_HASH = ${REV_SHA1}${MODIFIED}
TCM_APP_BUILD_STYLE = ${CONFIGURATION}
TCM_APP_BUILD_YEAR = ${YEAR}
EOL

# Mark the updated config file as unchanged for git
cd "${SRCROOT}"
git update-index --assume-unchanged "${REVISION_CONFIG_FILE}"
cd -

# Test if the final Info.plist needs to be removed, because a value changed
if [ -f "${CONFIGURATION_BUILD_DIR}/${INFOPLIST_PATH}" ]; then
echo "Info.plist exists, checking if update is needed."

# The Enviroment provides us the original values from a previous build.
if [ "${TCM_APP_REVISION}" != "${REV}${MODIFIED}" -o "${TCM_APP_REVISION_HASH}" != "${REV_SHA1}${MODIFIED}" -o "${TCM_APP_BUILD_STYLE}" != "${CONFIGURATION}" -o "${TCM_APP_BUILD_YEAR}" != "${YEAR}" ]; then
echo "Removing Info.plist from ${CONFIGURATION_BUILD_DIR}/${INFOPLIST_PATH}"
rm -f "${CONFIGURATION_BUILD_DIR}/${INFOPLIST_PATH}"
else
echo "Info.plist update not needed."
fi
fi
